FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Usar las variables de entorno que definimos en docker-compose
ENV VITE_WS_URL=http://localhost:3001
ENV VITE_API_URL=http://localhost:3001

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--port", "3000", "--host", "0.0.0.0"]