version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: redis_iot_service
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  sensor-publisher:
    build: 
      context: ./backend/publisher
      dockerfile: Dockerfile.publisher
    container_name: sensor_publisher
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

  web-subscriber:
    build:
      context: ./backend/subscriber
      dockerfile: Dockerfile.subscriber
    container_name: web_subscriber
    ports:
      - "3001:3000"  # ✅ Host:3001 -> Contenedor:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # NO incluyas PORT aquí, déjalo que use el default (3000)
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      - VITE_WS_URL=http://localhost:3001
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - web-subscriber
    restart: unless-stopped

volumes:
  redis_data: