FROM python:3.11-alpine

WORKDIR /app

# Copiar requirements primero
COPY requirements.txt .

# Instalar dependencias del sistema necesarias para compilar redis
RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    linux-headers \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

COPY publisher.py .

CMD ["python", "publisher.py"]